### ISSUE TITLE
how tf do you use it

### ISSUE THREAD

**Issue by CptMcMuffin** [ImpulsiveLad/CentralConfig#1]
the mod description doesnt tell shi about how to use it, would like a nerd to teach me

**Comment by ImpulsiveLass** [comment]
![Screenshot 2024-06-05 170425](https://github.com/ImpulsiveLad/CentralConfig/assets/92990441/6cad9ddd-8183-416b-b0aa-73379ef89564)
It is explained right here

The config is generated after you load a lobby and will be applied when after it has been generated
