### ISSUE TITLE
Modules can cause serious asynchronous issues

### ISSUE THREAD

**Issue by lenmon666** [ImpulsiveLad/CentralConfig#4]
When I use this mod, no matter which version it is! Because I have tested every version before!
As long as we use "weather coverage" and "trap coverage", even our good friends have the same configuration information! There may also be synchronization issues!
For example, in terms of weather, there are floods on my side, while my friend's side is in a normal state of sunshine!
The same goes for traps. In the process of thinking, I can see the traps on my body! There's nothing on my friend's side!
After deleting this mod file, all traps and weather will return to normal synchronization status!
Please check the module update and fix the synchronization issue between these two settings!
Do you still need these two configurations to experience better difficulty gameplay

**Comment by ImpulsiveLass** [comment]
1. Are the config entries synced? Like did you give them your file or vice versa?
2. You tested every version, so you know weather setting settings are removed then, the only thing I could think of is if you mean the first day in particular because that would make sense to me.
3. Never heard of a trap desync before, I'm reworking how traps are handled soon. The only thing I change is the # of traps.

**Comment by lenmon666** [comment]
> 1. 配置条目是否同步？比如你把你的文件给了他们，还是反之亦然？
> 2. 你测试了每个版本，所以你知道天气设置设置被删除了，我唯一能想到的是你是否特别指的是第一天，因为这对我来说是有意义的。
> 3. 以前从未听说过 trap 不同步，我很快就会重新设计 trap 的处理方式。我唯一更改的是陷阱的 #。

Because I directly adjusted all the mods we want to play, made them into compressed rar files, and gave them directly to my friends! That means the configuration information is the same! Because they all play directly and won't even modify these settings!
Not only will there be asynchronous issues on the first day! Later on, I noticed that my friend also mentioned to me in his voice the differences between his side and mine!

**Comment by ImpulsiveLass** [comment]
You compressed each separate mod into .rar files? Are you talking about the .dll files for the mods?

**Comment by lenmon666** [comment]
> 您将每个单独的 Mod 压缩成 .rar 个文件？你说的是 Mod 的 .dll 文件吗？

I compressed all the mods we want to play, including the configuration files, into RAR files for my friends!
After adjusting the R2MOD manager directly! Just like the mod integration package style

**Comment by lenmon666** [comment]
> 您将每个单独的 Mod 压缩成 .rar 个文件？你说的是 Mod 的 .dll 文件吗？

After my friends receive the RAR mod package, they can directly use it by extracting it from the game installation directory! Because the mods and configuration files we want to play have already been packaged!! Not a compressed single DLL file!!

**Comment by ImpulsiveLass** [comment]
So all the .cgfs are wrapped then? Can you send the hosts and clients?
All weather selection code has been removed so weathers are only set by vanilla and rpced through it.
Do you remember what traps on what moon in specific? IE turrets on rend could be a likely target for a desync if the individual spawnableMapObjects require separate network properties to be set

**Comment by lenmon666** [comment]
> So all the .cgfs are wrapped then? Can you send the hosts and clients? All weather selection code has been removed so weathers are only set by vanilla and rpced through it. Do you remember what traps on what moon in specific? IE turrets on rend could be a likely target for a desync if the individual spawnableMapObjects require separate network properties to be set

LandMine, Turret, and SpikeTrap! Most of these three types of traps will encounter asynchronous issues!
At present, there may also be synchronization issues with official maps!
I often play Aerona By Turbotaliz, which is https://thunderstore.io/c/lethal-company/p/Turbotaliz/Aerona/

**Comment by lenmon666** [comment]
> 那么所有的 .cgfs 都被包装了吗？您能否将主机和客户端发送给您？所有天气选择代码已被删除，因此天气只能由原版设置并通过它进行 rpced。你还记得哪个月球上具体有什么陷阱吗？如果单个 spawnableMapObject 需要设置单独的网络属性，则 rend 上的 IE 炮塔可能成为不同步的目标

Can you send the hosts and clients！ What are you referring to??

**Comment by ImpulsiveLass** [comment]
Tested rigorously.

I could not find a trap desync, even when the client doesn't have any config for CentralConfig, the host solely decides the spawning of traps, scrap, enemies, and the dungeon (selection and its size).

Weather was desynced on day 1 for the exact reason I believed. It is patched and will be in the next build.

**Comment by lenmon666** [comment]
> 经过严格测试。
> 
> 我找不到陷阱不同步，即使客户端没有任何 CentralConfig 的配置，主机也完全决定陷阱、废料、敌人和地牢（选择及其大小）的生成。
> 
> 天气在第 1 天不同步，正是因为我相信的原因。它已修补，并将在下一个版本中提供。

Okay, thank you very much. After you release it, I will update the version in a timely manner and continue to try!
I'll give you feedback again
If I use the EnemySPawner mod in combination with it at the same time-- https://thunderstore.io/c/lethal-company/p/StudioBeta/EnemySpawner/
Or rather, I can use the MoreEnemies mod in combination with it-- https://thunderstore.io/c/lethal-company/p/OpJosMods/MoreEnemies/
Will there be such a problem of asynchronous traps!
I hope you can take a look at the above two monster refreshing mods and see if using them together will result in this! Because I encountered problems when using it in this way!

**Comment by lenmon666** [comment]
> 经过严格测试。
> 
> 我找不到陷阱不同步，即使客户端没有任何 CentralConfig 的配置，主机也完全决定陷阱、废料、敌人和地牢（选择及其大小）的生成。
> 
> 天气在第 1 天不同步，正是因为我相信的原因。它已修补，并将在下一个版本中提供。

After teaming up again for gameplay testing, the latest version has now resolved the issue of out of sync! Thank you very much for your repair and improvement

**Comment by ImpulsiveLass** [comment]
Awesome, 0.12.5 made the host do all host stuff only and 0.12.6 rewrote a lot of internal methods that should optimize the mod a bunch
