### ISSUE TITLE
Minimum/Maximum Total Scrap Value?

### ISSUE THREAD

**Issue by Blob336** [ImpulsiveLad/CentralConfig#5]
Could you possibly add a setting in CentralConfig config for Minimum/Maximum Total Scrap Value? This setting is present in LethalLevelLoader config.

**Comment by ImpulsiveLass** [comment]
ahhhh yes, this question again.

TotalScrapValue does NOTHING in the game and never has.

Scrap is chosen to spawn based on the selected scrap count between the moon's min and max. What the scrap will be is decided by the scrap list for the moon.

the total scrap in the level is simply the added total of the scrap on the moon's individual values.

the max is never acce
![Screenshot 2024-09-06 170841](https://github.com/user-attachments/assets/89004ef5-3fe5-4eab-bdfe-6cdfb323dc6c)
ssed, and the min is only logged in the game's code.

Neither play any role in deciding how much scrap will spawn.
