### ISSUE TITLE
Scrap value multiplier doesn't work correctly

### ISSUE THREAD

**Issue by Blob336** [ImpulsiveLad/CentralConfig#6]
I set scrap value multiplier for Experimentation = 1, Rend = 2, Titan = 3 and Artifice = 5.
Landing on Artifice after landing on Titan resulted in 34000 Total Scrap Value, which is roughly 15 times more than default.
Landing on Experimentation after landing on Artifice resulted in 1600 Total Scrap Value, which is roughly 5 times more than default.
Landing on Rend after landing on Artifice resulted in 13000 Total Scrap Value, which is roughly 10 times more than default.

**Comment by ImpulsiveLass** [comment]
That adds up, the vanilla scrap value multiplier is 0.4
