### ISSUE TITLE
[Compat Issue] Central Config stops functioning with Diversity installed

### ISSUE THREAD

**Issue by Reshirou** [ImpulsiveLad/CentralConfig#9]
As of the latest updates, all changes made to moons with CenCon simply do not work if Diversity is installed, even with every single feature in Diversity turned off/set to false.

I've no idea which mod is "at fault" but I posted this to Diversity's discord issues channel too.

**Comment by ImpulsiveLass** [comment]
Do you have any logs?

**Comment by Reshirou** [comment]
I can get you some; where are latest logs stored?

**Comment by ImpulsiveLass** [comment]
BepInEx>LogOutput.log

**Comment by Reshirou** [comment]
EDIT: Here's also a clean profile with just the two mods and my config
`019315c0-7b46-8a1a-c4e1-764edd332a7f`

Tested here with Diversity using standard untouched config, and an arbitrary custom CentralConfig test that SHOULD make the price ordered moons list appear as follows:

March
Adamance
Vow

Assurance
Offense
Experimentation

Titan
Rend
Dine
But for some reason a whole bunch of the changes just did not work at all. Strangely, Experimentation is literally the only moon that got changed actually.

Attached is my CentralCOnfig config (made into a txt), LogOut;put, and a screenshot of what I see in the terminal with Diversity and without Diversity


[LogOutput.log](https://github.com/user-attachments/files/17691127/LogOutput.log)

[impulse.CentralConfig.txt](https://github.com/user-attachments/files/17691130/impulse.CentralConfig.txt)

With Diversity ↓
![With_Diversity](https://github.com/user-attachments/assets/cd90931f-9bc8-49fb-9c39-f919710e2a52)
Without Diversity ↓
![Without_Diversity](https://github.com/user-attachments/assets/099e0cdc-609f-465f-8b6f-500d1d63e9de)

**Comment by Reshirou** [comment]
From Chaos on the Diversity Discord:
"An error from CC. Not handling custom enemies correctly? Clamping Enemy Rarity That I've noticed. Let them know about that."
(I mentioned other creature mods dont bug cc out)
"Hmm The only difference they have with Diversity is that they all use LethalLib... Which I don't use... CC maybe is based on lethal lib?
Central config does need lethal lib in order to work. That's my best guess when it comes to Diversity"

**Comment by ImpulsiveLass** [comment]
I read the log, yeah it’s not accessing the walker, probably renamed it from `longboitype`

**Comment by ImpulsiveLass** [comment]
yesn't

he recoded EVERYTHING with 3.0.0 so I needed a new dll and the walker enemytype is local so I had to load it but yes now CC works just fine with diversity 3.0.x


now I gotta check the other 38 mods that updated in my pack....


Thats probably alright tho, I must COOK a very yummy feature before I push this build :3

**Comment by Reshirou** [comment]
Aw hell yeah, you love to see it. Thanks for looking into it and being a cool dev.

**Comment by ImpulsiveLass** [comment]
Decided to push now, other code being an ass,

Fixed by 0.15.6
